name: Axe

on:
  push:
    branches:
      - master
      - aXe
  pull_request:
    branches:
      - master
      - aXe

jobs:
  axe:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm install -g gatsby-cli@2.12.34
      - run: gatsby build
      - run: ls -la public
      - run: gatsby develop & npx wait-on http://localhost:8000
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:8000 --exit
